language: php
dist: focal

addons:
    apt:
        packages:
            - docker-ce

services:
    - docker

jobs:
    allow_failures:
        -   php: 'nightly'
    fast_finish: true

before_script:
    - docker --version
    - docker-compose --version

script:
    - make ci
